version: "3.8"

services:

  db-server:
    image: postgres:alpine
    container_name: gitcon-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: gitcon-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gitcon.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db-server

volumes:
  postgres_data: