version: "3.8"

services:

  db-server:
    image: postgres:alpine
    container_name: gitcon-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  pgadmin:
    build:
      context: ./pgadmin
    container_name: gitcon-pgadmin
    env_file:
      - .env
    environment:
      - DB_HOST=db-server   
    ports:
      - "5050:80"
    depends_on:
      - db-server

volumes:
  postgres_data: