version: "3.8"

services:

  spring-server:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    container_name: gitcon-spring-server
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - DB_HOST=db-server   
    depends_on:
      - db-server

  ui:
    build:
      context: ../Gitcon-UI
      dockerfile: Dockerfile
    container_name: gitcon-ui
    volumes:
      - frontend_dist:/usr/share/nginx/html

  nginx:
    image: nginx:alpine
    container_name: gitcon-nginx
    ports:
      - "80:80"
    volumes:
      - frontend_dist:/usr/share/nginx/html:ro
      - ./nginx/nginx.prod.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - ui
      - spring-server

  db-server:
    image: postgres:alpine
    container_name: gitcon-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  pgadmin:
    build:
      context: ./pgadmin
    container_name: gitcon-pgadmin
    env_file:
      - .env
    environment:
      - DB_HOST=db-server   
    ports:
      - "5050:80"
    depends_on:
      - db-server

volumes:
  postgres_data:
  frontend_dist: